"""empty message

Revision ID: 1766849b259f
Revises: 5c987ccc146e
Create Date: 2025-12-18 13:19:39.551045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1766849b259f'
down_revision = '5c987ccc146e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumer_complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_of_complaint', sa.Text(), nullable=True))
        batch_op.alter_column('sector_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('value_of_complaint',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('date_of_resolution',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumer_complaints', schema=None) as batch_op:
        batch_op.alter_column('date_of_resolution',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('value_of_complaint',
               existing_type=sa.String(length=255),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('sector_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('status_of_complaint')

    # ### end Alembic commands ###
