"""add enforcement operations table

Revision ID: 395c955eab98
Revises: 4c03ef12b2ed
Create Date: 2025-12-29 11:36:05.432337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395c955eab98'
down_revision = '4c03ef12b2ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psr_enforcement_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_report_id', sa.Integer(), nullable=False),
    sa.Column('sector_classification', sa.String(length=255), nullable=True),
    sa.Column('date_commenced', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('item_description_qty', sa.Text(), nullable=True),
    sa.Column('total_weight', sa.String(length=100), nullable=True),
    sa.Column('total_value', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_report_id'], ['program_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_report_id')
    )
    op.drop_table('seizure_reports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seizure_reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sector_classification', sa.VARCHAR(length=100), nullable=True),
    sa.Column('date_commenced', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('objectives', sa.TEXT(), nullable=True),
    sa.Column('location_address', sa.TEXT(), nullable=True),
    sa.Column('action_taken', sa.TEXT(), nullable=True),
    sa.Column('item_description_qty', sa.TEXT(), nullable=True),
    sa.Column('total_weight', sa.VARCHAR(length=50), nullable=True),
    sa.Column('total_value', sa.VARCHAR(length=100), nullable=True),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['program_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('psr_enforcement_operations')
    # ### end Alembic commands ###
