"""Add status column to program_reports

Revision ID: 39d0940f6ff5
Revises: 64585dceab3e
Create Date: 2026-02-05 20:26:42.012072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d0940f6ff5'
down_revision = '64585dceab3e'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('program_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), 
                                      nullable=False, 
                                      server_default='submitted'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('program_reports', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
