"""empty message

Revision ID: 4c03ef12b2ed
Revises: 1766849b259f
Create Date: 2025-12-18 15:36:20.518321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c03ef12b2ed'
down_revision = '1766849b259f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seizure_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_classification', sa.String(length=100), nullable=True),
    sa.Column('date_commenced', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('item_description_qty', sa.Text(), nullable=True),
    sa.Column('total_weight', sa.String(length=50), nullable=True),
    sa.Column('total_value', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['program_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seizure_reports')
    # ### end Alembic commands ###
