"""Added ConsumerComplaint model for Templates 3, 4, 5

Revision ID: 5c987ccc146e
Revises: d89dfe6c8657
Create Date: 2025-12-17 02:39:46.046394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c987ccc146e'
down_revision = 'd89dfe6c8657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumer_complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('case_file_no', sa.String(length=50), nullable=False),
    sa.Column('sector_category', sa.String(length=100), nullable=False),
    sa.Column('date_received', sa.DateTime(), nullable=False),
    sa.Column('complaint_details', sa.Text(), nullable=False),
    sa.Column('complainant_details', sa.Text(), nullable=False),
    sa.Column('respondent_details', sa.Text(), nullable=False),
    sa.Column('value_of_complaint', sa.Float(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('date_of_resolution', sa.Date(), nullable=True),
    sa.Column('complainant_remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_file_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumer_complaints')
    # ### end Alembic commands ###
