"""Add date_ended to program_reports

Revision ID: 69d8ad3f486d
Revises: 39d0940f6ff5
Create Date: 2026-03-02 21:01:46.993250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d8ad3f486d'
down_revision = '39d0940f6ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_ended', sa.Date(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('program_reports', schema=None) as batch_op:
        batch_op.drop_column('date_ended')

    # ### end Alembic commands ###
