"""add psr dynamic tables

Revision ID: 71301421f8f5
Revises: 395c955eab98
Create Date: 2026-01-11 18:58:34.580511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71301421f8f5'
down_revision = '395c955eab98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psr_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_report_id'], ['program_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psr_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['row_id'], ['psr_rows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psr_field_values')
    op.drop_table('psr_rows')
    # ### end Alembic commands ###
