"""Add new fields for Template 1 (date_started, previous_status_percentage, constraints_requirements)

Revision ID: 8b32f6275f86
Revises: 
Create Date: 2025-12-11 19:43:38.094151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b32f6275f86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_started', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('previous_status_percentage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('constraints_requirements', sa.Text(), nullable=True))
        batch_op.alter_column('report_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_reports', schema=None) as batch_op:
        batch_op.alter_column('report_type',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('constraints_requirements')
        batch_op.drop_column('previous_status_percentage')
        batch_op.drop_column('date_started')

    # ### end Alembic commands ###
