"""Added TargetsAchievedReport table for Template 2

Revision ID: d89dfe6c8657
Revises: 8b32f6275f86
Create Date: 2025-12-16 16:31:59.652625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89dfe6c8657'
down_revision = '8b32f6275f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets_achieved_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_description', sa.Text(), nullable=False),
    sa.Column('achievement_value', sa.Integer(), nullable=True),
    sa.Column('target_remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['program_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('targets_achieved_reports')
    # ### end Alembic commands ###
